### ISSUE TITLE
Add hotel prices to output 

### ISSUE THREAD

**Issue by piramalakia** [apify-projects/store-crawler-google-places#261] opened 2022-05-05 13:47 UTC
I tried to run the actor with several parameter combinations to scrape "Hotels" data for a specific location (url input) and it seems that the "price" field is not being scraped, 
All the rest is working perfectly.

I'm attaching a sample output.
Thanks for the help
[dataset_crawler-google-places_2022-05-05_11-42-53-698.xlsx](https://github.com/drobnikj/crawler-google-places/files/8631700/dataset_crawler-google-places_2022-05-05_11-42-53-698.xlsx)

**Comment by metalwarrior665** [comment] 2023-01-04 00:08
The current price is mainly for restaurants, it is the `$$` that is shown near the place title.

Your example has hotels, e.g. https://www.google.com/maps/place/Hotel+Akbar+International/@33.6072333,73.0641573,17z/data=!4m8!3m7!1s0x38df94bd80d333ed:0xb4200d5de0832b0a!5m2!4m1!1i2!8m2!3d33.6072333!4d73.0641573!8zGTscXSAgIEBAIUskLCAbRFJA?hl=en

which have the actual hotel pricing.

This a new feature that we can add, I'm renaming the issue

**Comment by metalwarrior665** [comment] 2023-01-04 00:13
Actually this is duplicate of https://github.com/apify-projects/store-crawler-google-places/issues/233 so closing this

**Closed by metalwarrior665** 2023-01-04 00:13 UTC
Labels: enhancement, low priority
