### ISSUE TITLE
Why some address is not fetched?

### ISSUE THREAD

**Issue by beshoo** [apify-projects/store-crawler-google-places#198] opened 2021-09-26 02:17 UTC
While am reviewing the Log. open google search URL. I can see a lot of address which related to the search keyword is not fetched.

```
INFO  [SEARCH]: Enqueued 0/20 places (correct location/total) + 0 ads --- https://www.google.com/maps/search/%D8%AA%D8%B9%D9%84%D9%8A%D9%85+%D9%84%D8%BA%D8%A7%D8%AA%E2%80%AD/@24.650611,46.6975732,12z?hl=en
WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJ4ezrGzsFLz4RZ3Q6HyqLmIY
WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJQWFRdWMDLz4RFKMUGrLuw1A
WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJN-evSKMELz4R-wWcdHRpl10
INFO  [SEARCH]: Enqueued 0/13 places (correct location/total) + 0 ads --- https://www.google.com/maps/search/%D8%AA%D8%B9%D9%84%D9%8A%D9%85+%D9%84%D8%BA%D8%A7%D8%AA%E2%80%AD/@24.650611,46.6975732,12z?hl=en
WARN  [SEARCH]: Finishing search because there are no more pages --- تعليم لغات - https://www.google.com/maps/@24.65062728383304,46.76323608640613,1 

INFO  [STATS]: failed: 0 | ok: 138 | outOfPolygon: 13776 | outOfPolygonCached: 13776 | places: 25 | maps: 113
INFO  Scraping finished!
```
For example, this address is not listed in the out results.
![image](https://user-images.githubusercontent.com/4635115/134790762-201d9192-4e4f-487d-bdbe-0f1162320d2b.png)

Here are the output search results:
https://beshoo.com/mussab/ksa_5/datasets/default/

the input is as following
```
{
  searchStringsArray: [ 'تعليم لغات' ],
  country: 'السعودية',
  city: 'الرياض',
  county: '',
  postalCode: '',
  maxCrawledPlaces: 10000,
  maxCrawledPlacesPerSearch: 1000,
  maxReviews: 0,
  language: 'en',
  maxImages: 1,
  includeHistogram: false,
  includeOpeningHours: false,
  includePeopleAlsoSearch: false,
  additionalInfo: false,
  reviewsSort: 'mostRelevant',
  reviewsTranslation: 'onlyTranslated',
  exportPlaceUrls: false,
  zoom: 16,
  maxAutomaticZoomOut: 14,
  proxyConfig: {
    useApifyProxy: true,
  },
  maxConcurrency: 2,
  maxPageRetries: 0,
  pageLoadTimeoutSec: 60,
  maxPagesPerBrowser: 10,
  useChrome: true,
  useStealth: true,
  launchOptions: { headless: true },
  scrapeReviewerName: false,
  scrapeReviewerId: false,
  scrapeReviewerUrl: false,
  scrapeReviewId: false,
  scrapeReviewUrl: false,
  scrapeResponseFromOwnerText: false,
  debug: false
}
```

Even the reported place is not available in the results.
`WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJ4ezrGzsFLz4RZ3Q6HyqLmIY`

**Comment by metalwarrior665** [comment] 2021-09-27 07:24
Maybe it was considered outOfPolygon for that country/city? You can also try to run it headful with (`headless:false`) to see how it is scraping.

**Comment by beshoo** [comment] 2021-09-27 10:47
Definitely, there is a problem, am searching for an educational institution in Saudi Arabia, the capital, only 25 results returned!
I am not sure how the crawler decides the results outOfPolygon!
I will try to "`headless:false`" but do you believe it is reasonable?

**Comment by beshoo** [comment] 2021-09-27 11:15
SOLVED

**Comment by metalwarrior665** [comment] 2021-09-27 11:28
What solved it?

**Comment by beshoo** [comment] 2021-09-27 11:58
Well, it seems not, and using headless:false is not helping much, I sow that it open the place but it is not saved in it to the output JSON dataset.

**moreover, why crawler saves the errors as JSON files within the dataset.**

all these addresses are related to the keyword am searching for and it is not **outOfPolygon**.
```
INFO  [SEARCH]: Start enqueuing places details for search --- تعليم لغات https://www.google.com/maps/@24.65062728383304,46.68595769046881,16z/search?hl=en
WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJq3Kc1loPLz4Rtu16MEihrZE
WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJdfvQ_ZQELz4RPvxD5-mx4Ps
WARN  Google presented already enqueued place, skipping... --- https://www.google.com/maps/search/?api=1&query=تعليم لغات&query_place_id=ChIJWVaMnJYELz4RTFtuseYc09M
```

the input
```

{
  searchStringsArray: [ 'تعليم لغات' ],
  country: 'السعودية',
  city: 'الرياض',
  county: '',
  postalCode: '',
  maxCrawledPlaces: 10000,
  maxCrawledPlacesPerSearch: 1000,
  maxReviews: 0,
  language: 'en',
  maxImages: 1,
  includeHistogram: false,
  includeOpeningHours: false,
  includePeopleAlsoSearch: false,
  additionalInfo: false,
  reviewsSort: 'mostRelevant',
  reviewsTranslation: 'onlyTranslated',
  exportPlaceUrls: false,
  zoom: 16,
  maxAutomaticZoomOut: 14,
  proxyConfig: {
    useApifyProxy: true,
  },
  maxConcurrency: 2,
  maxPageRetries: 0,
  pageLoadTimeoutSec: 60,
  maxPagesPerBrowser: 10,
  useChrome: true,
  useStealth: true,
  launchOptions: { headless: true },
  scrapeReviewerName: false,
  scrapeReviewerId: false,
  scrapeReviewerUrl: false,
  scrapeReviewId: false,
  scrapeReviewUrl: false,
  scrapeResponseFromOwnerText: false,
  debug: false
}

```

**Comment by beshoo** [comment] 2021-09-27 13:19
@metalwarrior665
I test it more than 10 scenarios and for some reason, a lot of related and correct addresses is ignored by this message:
**`Google presented already enqueued place, skipping`**

What is the problem, do you have any idea?

**Comment by beshoo** [comment] 2021-09-28 02:52
Dear @metalwarrior665.
Am still confused with this message "Google presented already enqueued place, skipping" is it a **BUG**?

While the address is valid, why crawler is skipping it? 
What is the meaning of "**enqueued place**"? if the address is "queued" why it is not present in the dataset?
And why crawler save timeout errors as JSON files with the json dataset files?

Waiting for your kindly reply.

**Comment by beshoo** [comment] 2021-10-02 13:25
@metalwarrior665 any update about this bug?

**Comment by metalwarrior665** [comment] 2023-01-04 00:16
Sorry for missing this issue. Already enqueued means that we will (or did) scrape this place already.

I suspect the original issue might have been caused by different zoom. Closing this for now

**Closed by metalwarrior665** 2023-01-04 00:16 UTC
